[package]
name = "setup_core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
parking_lot.workspace = true
rayon = "1"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
service_db = { package = "db", version = "0.1", path = "../../crates/db" }
